-- relevant inpatient and outpatient care during FU

select *,
ROW_NUMBER() OVER(ORDER BY 1) AS rownum
from sr3452058_table2_enc_ip_op
where enc_type = 'Ambulatory' and
    upper(provider_specialty) in ('ACUTE CARE NURSE PRACTITIONER','ADULT HEALTH NURSE PRACTITIONER','GENERAL PRACTICE','GYNECOLOGY, GENERAL'
    ,'GYNECOLOGY, REPRODUCTIVE ENDOCRINOLOGY','GYNECOLOGY, URO-GYNECOLOGY','MEDICINE, ADULT','MEDICINE, ENDOCRINOLOGY','MEDICINE, ENDOCRINOLOGY, DIABETES, OBESITY, METABOLISM'
    ,'MEDICINE, FAMILY MEDICINE','MEDICINE, INTERNAL MEDICINE','NURSE PRACTITIONER','OBSTETRICS & GYNECOLOGY','OBSTETRICS & GYNECOLOGY NURSE PRACTITIONER'
    ,'OBSTETRICS GYNECOLOGY, GENERAL','OBSTETRICS, GENERAL','OBSTETRICS, MATERNAL FETAL MEDICINE','UROLOGY, URO-GYNECOLOGY',"WOMEN'S HEALTH NURSE PRACTITIONER"
    ,'EMERGENCY MEDICINE, ADULT','EMERGENCY MEDICINE, GENERAL','EMERGENCY MEDICINE, PEDIATRICS','FAMILY NURSE PRACTITIONER','GYNECOLOGY, GYNECOLOGIC ONCOLOGY'
    ,'PEDIATRIC ENDOCRINOLOGY','PEDIATRIC NURSE PRACTITIONER' ,'PEDIATRICS, ADOLESCENT MEDICINE','PEDIATRICS, GENERAL','PHYSICIAN ASSISTANT'
    ,'PHYSICIAN ASSISTANT, MEDICAL','REGISTERED NURSE','URGENT CARE')
ORDER BY rownum
LIMIT 500000;
--OFFSET 500000

-- for some reason cannot offset by 1Mil, so use this instead
with outpatient as (
select *,
ROW_NUMBER() OVER(ORDER BY 1) AS rownum
from sr3452058_table2_enc_ip_op
where enc_type = 'Ambulatory' and
    upper(provider_specialty) in ('ACUTE CARE NURSE PRACTITIONER','ADULT HEALTH NURSE PRACTITIONER','GENERAL PRACTICE','GYNECOLOGY, GENERAL'
    ,'GYNECOLOGY, REPRODUCTIVE ENDOCRINOLOGY','GYNECOLOGY, URO-GYNECOLOGY','MEDICINE, ADULT','MEDICINE, ENDOCRINOLOGY','MEDICINE, ENDOCRINOLOGY, DIABETES, OBESITY, METABOLISM'
    ,'MEDICINE, FAMILY MEDICINE','MEDICINE, INTERNAL MEDICINE','NURSE PRACTITIONER','OBSTETRICS & GYNECOLOGY','OBSTETRICS & GYNECOLOGY NURSE PRACTITIONER'
    ,'OBSTETRICS GYNECOLOGY, GENERAL','OBSTETRICS, GENERAL','OBSTETRICS, MATERNAL FETAL MEDICINE','UROLOGY, URO-GYNECOLOGY',"WOMEN'S HEALTH NURSE PRACTITIONER"
    ,'EMERGENCY MEDICINE, ADULT','EMERGENCY MEDICINE, GENERAL','EMERGENCY MEDICINE, PEDIATRICS','FAMILY NURSE PRACTITIONER','GYNECOLOGY, GYNECOLOGIC ONCOLOGY'
    ,'PEDIATRIC ENDOCRINOLOGY','PEDIATRIC NURSE PRACTITIONER' ,'PEDIATRICS, ADOLESCENT MEDICINE','PEDIATRICS, GENERAL','PHYSICIAN ASSISTANT'
    ,'PHYSICIAN ASSISTANT, MEDICAL','REGISTERED NURSE','URGENT CARE')
    )

SELECT *
FROM outpatient
WHERE rownum > 1000000