-- extract all relevant telemedicine encounters

select *
from sr3452058_table2_enc_ip_op
where enc_type = 'Telemedicine' and
    upper(provider_specialty) in ('ACUTE CARE NURSE PRACTITIONER','ADULT HEALTH NURSE PRACTITIONER','GENERAL PRACTICE','GYNECOLOGY, GENERAL'
    ,'GYNECOLOGY, REPRODUCTIVE ENDOCRINOLOGY','GYNECOLOGY, URO-GYNECOLOGY','MEDICINE, ADULT','MEDICINE, ENDOCRINOLOGY','MEDICINE, ENDOCRINOLOGY, DIABETES, OBESITY, METABOLISM'
    ,'MEDICINE, FAMILY MEDICINE','MEDICINE, INTERNAL MEDICINE','NURSE PRACTITIONER','OBSTETRICS & GYNECOLOGY','OBSTETRICS & GYNECOLOGY NURSE PRACTITIONER'
    ,'OBSTETRICS GYNECOLOGY, GENERAL','OBSTETRICS, GENERAL','OBSTETRICS, MATERNAL FETAL MEDICINE','UROLOGY, URO-GYNECOLOGY',"WOMEN'S HEALTH NURSE PRACTITIONER"
    ,'EMERGENCY MEDICINE, ADULT','EMERGENCY MEDICINE, GENERAL','EMERGENCY MEDICINE, PEDIATRICS','FAMILY NURSE PRACTITIONER','GYNECOLOGY, GYNECOLOGIC ONCOLOGY'
    ,'PEDIATRIC ENDOCRINOLOGY','PEDIATRIC NURSE PRACTITIONER' ,'PEDIATRICS, ADOLESCENT MEDICINE','PEDIATRICS, GENERAL','PHYSICIAN ASSISTANT'
    ,'PHYSICIAN ASSISTANT, MEDICAL','REGISTERED NURSE','URGENT CARE')
