-- FINAL time downloading the encounter data for relevant encounters by year since 
-- there are MUCH more than 500K rows

select *
from sr3452058_table2_enc_ip_op
where (upper(provider_specialty) in ('ACUTE CARE NURSE PRACTITIONER','ADULT HEALTH NURSE PRACTITIONER','GENERAL PRACTICE','GYNECOLOGY, GENERAL'
    ,'GYNECOLOGY, REPRODUCTIVE ENDOCRINOLOGY','GYNECOLOGY, URO-GYNECOLOGY','MEDICINE, ADULT','MEDICINE, ENDOCRINOLOGY','MEDICINE, ENDOCRINOLOGY, DIABETES, OBESITY, METABOLISM'
    ,'MEDICINE, FAMILY MEDICINE','MEDICINE, INTERNAL MEDICINE','NURSE PRACTITIONER','OBSTETRICS & GYNECOLOGY','OBSTETRICS & GYNECOLOGY NURSE PRACTITIONER'
    ,'OBSTETRICS GYNECOLOGY, GENERAL','OBSTETRICS, GENERAL','OBSTETRICS, MATERNAL FETAL MEDICINE','UROLOGY, URO-GYNECOLOGY',"WOMEN'S HEALTH NURSE PRACTITIONER"
    ,'EMERGENCY MEDICINE, ADULT','EMERGENCY MEDICINE, GENERAL','EMERGENCY MEDICINE, PEDIATRICS','FAMILY NURSE PRACTITIONER','GYNECOLOGY, GYNECOLOGIC ONCOLOGY'
    ,'PEDIATRIC ENDOCRINOLOGY','PEDIATRIC NURSE PRACTITIONER' ,'PEDIATRICS, ADOLESCENT MEDICINE','PEDIATRICS, GENERAL','PHYSICIAN ASSISTANT'
    ,'PHYSICIAN ASSISTANT, MEDICAL','REGISTERED NURSE','URGENT CARE') or 
    (regexp_like(lower(adt_service), 'general|obstetrics|gynecology|urology|endocrinology|emergency|family|radiology') and
    adt_service not like '%Neurology%')) and
    -- enc_date >= '2016-08-01' and enc_date <= '2017-12-31'
    -- enc_date >= '2018-01-01' and enc_date <= '2019-12-31'
    -- enc_date >= '2020-01-01' and enc_date <= '2021-12-31'
    -- enc_date >= '2022-01-01' and enc_date <= '2023-08-01'
